### ISSUE TITLE
What is emissionCurveDataPoints?

### ISSUE THREAD

**Issue by n8tb1t** [turtlecoin/blockchain-explorer#2]
Guys, help me please!

What is:
```
 emissionCurveInterval: 20000,
emissionCurveDataPoints: 15000,
```
in config file, how you calculate this ?

**Comment by brandonlehmann** [comment]
You don’t calculate it. Curve interval is how many blocks between data points. Data points is how many data points to graph. Pick some numbers and try them until you’re happy with the results.
