### ISSUE TITLE
Public nodes with SSL disappeared

### ISSUE THREAD

**Issue by jongcs** [turtlecoin/blockchain-explorer#26]
Some of the nodes with Let's Encrypt SSL certificate has been disappeared from the explorer for a while.
https://node.faircryptocoins.xyz/info
https://turtlecoin.publicnode.eu/info

I think it might because of their old root certificate DST Root CA X3 expired last month.
You might need to update your explorer server to trust Let's Encrypt's new root certificate ISRG Root X1.

**Comment by brandonlehmann** [comment]
Node polling does not currently validate certificates (ie. accepts certs even if they aren't trusted). Logging indicates that those URLs are currently filtering (blocking) the polling request(s).

**Comment by jongcs** [comment]
![screenshot](https://user-images.githubusercontent.com/21971007/140803683-7657ba4a-06d1-4900-8bab-b25cc6b73b6a.png)
My SSL node just been marked as down since I switch to Let's Encrypt certificate.
